package org.neteinstein.pickaname.tools

import kotlinx.coroutines.runBlocking
import org.neteinstein.pickaname.data.parser.NameListTextParser
import org.neteinstein.pickaname.data.parser.PdfTextExtractor
import org.neteinstein.pickaname.domain.model.Gender
import org.neteinstein.pickaname.domain.model.NamesSourceDefaults
import java.net.HttpURLConnection
import java.net.URI
import java.nio.file.Files
import java.nio.file.Path
import java.time.Instant
import kotlin.system.exitProcess

/**
 * Downloads the official names PDF, parses it with the app's own parser, and writes the snapshot
 * the **web** build loads instead of downloading the PDF itself.
 *
 * The web build cannot fetch the source directly: it serves no `Access-Control-Allow-Origin`
 * header, so a browser blocks the request outright (MIGRATION_PLAN.md risk R3). Publishing a
 * snapshot next to the site turns that into a same-origin fetch, and has the side benefit that a
 * visitor's browser never parses a 2.9 MB PDF.
 *
 * Usage: `./gradlew :tools:names-snapshot:run --args="<output-file> [source-url]"`.
 */
fun main(args: Array<String>) = runBlocking {
    val outputPath = Path.of(args.firstOrNull() ?: DEFAULT_OUTPUT)
    val sourceUrl = args.getOrNull(1) ?: NamesSourceDefaults.DEFAULT_SOURCE_URL

    println("Downloading $sourceUrl")
    val pdfBytes = download(sourceUrl)
    println("Downloaded ${pdfBytes.size} bytes")

    val text = PdfTextExtractor().extractText(pdfBytes)
    val names = NameListTextParser().parse(text)
    if (names.isEmpty()) {
        System.err.println("Parsed 0 names - refusing to write an empty snapshot.")
        exitProcess(1)
    }
    println("Parsed ${names.size} names")

    val snapshot = buildString {
        appendLine("$COMMENT_PREFIX Portuguese allowed names, parsed from the official IRN list.")
        appendLine("$COMMENT_PREFIX Generated by tools/names-snapshot - do not edit by hand.")
        appendLine("$COMMENT_PREFIX generated: ${Instant.now()}")
        appendLine("$COMMENT_PREFIX source: $sourceUrl")
        appendLine("$COMMENT_PREFIX count: ${names.size}")
        names.forEach { name ->
            appendLine("${name.name}\t${name.gender.toSnapshotCode()}")
        }
    }

    Files.createDirectories(outputPath.parent)
    Files.writeString(outputPath, snapshot)
    println("Wrote $outputPath")
}

private fun download(url: String): ByteArray {
    val connection = URI(url).toURL().openConnection() as HttpURLConnection
    // The host answers 502 to requests without a User-Agent, so this is not optional.
    connection.setRequestProperty("User-Agent", USER_AGENT)
    connection.connectTimeout = 30_000
    connection.readTimeout = 120_000
    connection.inputStream.use { return it.readBytes() }
}

private fun Gender.toSnapshotCode(): String = when (this) {
    Gender.FEMALE -> "F"
    Gender.MALE -> "M"
}

private const val DEFAULT_OUTPUT = "webApp/src/wasmJsMain/resources/names-snapshot.tsv"
private const val COMMENT_PREFIX = "#"
private const val USER_AGENT =
    "Mozilla/5.0 (compatible; PickANameSnapshotBot/1.0; +https://github.com/neteinstein/portuguese-allowed-names)"
